### ISSUE TITLE
Check to make sure .fastq(.gz), and .bam are not included in the aggregated product

### ISSUE THREAD

**Issue by jluebeck** [AmpliconSuite/AmpliconSuiteAggregator#13]
To ensure large bam and fastq files are not included, we should sweep the aggregated files and remove any files ending with

- .fq
- .fq.gz
- .fastq
- .fastq.gz
- .bam
- .cram

**Comment by edwin5588** [comment]
Code has been added to exclude the list of extensions above. Will be updated together with the API integration. Can include more extensions to the exclusion list if necessary in the future.
