### ISSUE TITLE
Module warns about .tar.gz file not of supported type

### ISSUE THREAD

**Issue by jluebeck** [AmpliconSuite/AmpliconSuiteAggregator#14]
![Screen Shot 2023-05-10 at 3 56 46 PM](https://github.com/genepattern/AmpliconSuiteAggregator/assets/14268531/c80a3ce5-ef53-4a50-a889-7b902ef34942)

(See warning icon in image above) 
Runs fine, but warns user that the .tar.gz is not a compatible format. Warning doesn't seem to exist on the beta server - only the main server.

**Comment by edwin5588** [comment]
Hi Jens, 

Yeah this sometimes happens to me. I'll try to figure out why this occurs. 

Edwin

**Comment by edwin5588** [comment]
Hi Jens, 

Issue has been noted and has already been fixed. The changes are not yet pushed to the UCSD server. Ted will update the server in July. 

Edwin

**Comment by edwin5588** [comment]
Issue is fixed.
