### ISSUE TITLE
Looks like you're missing a space in the AmpliconSuiteAggregator.py call?

### ISSUE THREAD

**Issue by auberginekenobi** [AmpliconSuite/AmpliconSuiteAggregator#33]
Looks like you're missing a space in the ASR.py call?
genepattern.ucsd server, job 11715

=========================================

INFO:    Using cached SIF image
usage: AmpliconSuiteAggregator.py [-h]
                                  (-flist FILELIST | --files FILES [FILES ...])
                                  [-o OUTPUT_NAME] [-u USERNAME]
                                  [--upload_only {Yes,No}]
                                  [--name_map NAME_MAP] [-c {Yes,No}]
                                  [-s {dev,prod,local-debug}]
                                  [--ref {hg19,GRCh37,GRCh38,GRCh38_viral,mm10}]
                                  [--python3_path PYTHON3_PATH] [-v]
AmpliconSuiteAggregator.py: error: unrecognized arguments: --name_map/expanse/projects/mesirovlab/genepattern/servers/ucsd.prod/users/ochapman@eng.ucsd.edu/uploads/tmp/run1351716127104336940.tmp/name.map/1/2023-10-27_hg38_name_map.txt

**Comment by edwin5588** [comment]
Fix pushed to GP@UCSD, thanks for noticing this bug!
